# vi:syntax=yaml
name: Build Image and Push to Dockerhub

on:
  push:
    branches: main
  schedule:
    - cron: "3 2 * * 1"

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build A Docker Image and Push to Dockerhub
        run: |
          CONTAINER_IMAGE="mikemartin1090/aws-cli"
          CONTAINER_IMAGE_SHA="${CONTAINER_IMAGE}:${{github.sha}}"
          CONTAINER_IMAGE_LATEST="${CONTAINER_IMAGE}:latest"
          docker build -t $CONTAINER_IMAGE_SHA -t $CONTAINER_IMAGE_LATEST .
          docker push $CONTAINER_IMAGE_SHA
          docker push $CONTAINER_IMAGE_LATEST